name: Python Tests

on:
  pull_request:
    branches:
      - main  # Change to your default branch if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint coverage

      - name: Run tests with pytest
        run: |
          pytest --cov --pylint
        continue-on-error: false  # Fail the workflow if tests don't pass

      - name: Check coverage
        run: |
          coverage report --fail-under=100  # Enforce 100% coverage
        continue-on-error: false  # Fail the workflow if coverage is below 100%

  # Define a second job for preventing merge if tests and linting don't pass
  enforce:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Ensure tests and pylint passed
        run: |
          echo "All checks passed. Ready to merge."

    if: ${{ always() && success() }}  # Only allow if previous tests pass

# Optionally, you can add a branch protection rule for the `main` branch in GitHub settings to enforce this.
